// This is not a full list of commands
export enum Command {
  CMD_PAUSE = 'CMD_PAUSE',
  CMD_EXIT = 'CMD_EXIT',
  CMD_DIALPAD = 'CMD_DIALPAD',
  CMD_REQ_PAUSE_LIST = 'CMD_REQ_PAUSE_LIST',
  CMD_LOGOUT = 'CMD_LOGOUT',
  CMD_MAKECALL = 'CMD_MAKECALL',
  CMD_REQ_CRT_DETAILS = 'CMD_REQ_CRT_DETAILS',
  CMD_PREDICTIVE = 'CMD_PREDICTIVE',
}
